name: add

on: [push, pull_request]

jobs:
  test:
    name: Unit Test
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Run Python script
        run: python add.py

      
